/* eslint-disable */
import simLauncher from '../../joist/js/simLauncher.js';
const image = new Image();
const unlock = simLauncher.createLock( image );
image.onload = unlock;
image.src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAjJJREFUeNrcms1LVFEYh89MDZIYVBpqkptcWGYfQ85O3LRJS6lV7Vpoizbppj+g8D8Ii6CYleDCJAoRBN0ILaKSCnREkKlEiIZEhuhLr78Xz4HrxXHmcu7Hec8LzzDMLOY8857P956ECDZOg3PgFDgBqsF/cBD8Ad/AV/ABLMjvjIlu8AQsAscHKyALboIjcTW+BgyBTz4bX4of4BnoiFLitvw3nZB4CS6GKUD9fjpEAS/DYUj0gvUIJRRv5QQSSNyLQcBNEfToSgzGLOHmhs6gdgzjul+JtIESinSlElVyBTZVhNacw5WIPDJYQvGinEQbAwnFlf1EJhmJfAHJUjtXhxn9e4k8ZyiS80rQNvoXQxHisnD1sT5wSPCMW26Rq4Jv0OyVSuDlgFwAGxjLZCgjZ5hLUFwikfOCf7SSSKMFIidJ5LgFIkdJpNYCkToSSVggkiKR3xaIFEmkYIFIgUS+2yKyZIHIclLWb7eYi3xWb4IqRsfBJmhSu98Zxtl4B1aVyDhjkdfeD3IMuxWN7WbhqUI8ZpiNV7Kasivoed9PZhnJlDK8w0hioly6PjKQ+AfqbSibDlQ6iO4aLDHqd0YYMVDivaz6+I6sQRJ0U+KYzlxtQk14XldCxYMYJcboKBvkKnoN5COWuB/WloDS+zQCgSnh46GnVq1VpjxogVkRU0H9LHioeTDLyyx36TQkyJrWBdAJ2kGL3F6772HRTnsDrNEZW+zc75oDb8Bf3R/fFmAAks1mJ87mQ8UAAAAASUVORK5CYII=';
export default image;